version: "3.8"
services:
  php-apache-enviroment:
    container_name: php-apache
    image: php:8.0-apache
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db
