version: "3.1"

services:
  db:
    image: mysql
    container_name: mysqlpsait
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: psait11
      MYSQL_USER: psait11
      MYSQL_PASSWORD: psait11

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
